version: '3.7'
services:
    web:
        image: nginx:latest
        ports:
            - "8083:8083"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:delegated
            - ./app:/app:delegated
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app:delegated
        restart: always
    cron:
        build:
            context: .
            dockerfile: CRON.Dockerfile
        restart: always
        volumes:
            - ./app:/app:delegated
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'purple'
            MYSQL_USER: 'moodleuser'
            MYSQL_PASSWORD: 'moodlepass'
            MYSQL_DATABASE: 'moodle50'
        restart: always
        volumes:
            - mysqldata:/var/lib/mysql:delegated
        ports:
            - 3309:3306
    redis:
        image: redis:latest
        ports:
          - "6381:6379"
        restart: always
volumes:
    mysqldata: {}

